// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop'];
    ACol: typeof import('ant-design-vue/es')['Col'];
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
    AImage: typeof import('ant-design-vue/es')['Image'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ARow: typeof import('ant-design-vue/es')['Row'];
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink'];
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText'];
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
