// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop'];
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink'];
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText'];
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
