import { defineConfig } from 'windicss/helpers';
import * as antdColors from '@ant-design/colors';
import aspectRatioPlugin from 'windicss/plugin/aspect-ratio';
import formsPlugin from 'windicss/plugin/forms';
import filtersPlugin from 'windicss/plugin/filters';
import lineClampPlugin from 'windicss/plugin/line-clamp';
import scrollSnapPlugin from 'windicss/plugin/scroll-snap';
import typographyPlugin from 'windicss/plugin/typography';
// @ts-ignore
import animationsPlugin from '@windicss/plugin-animations';
// @ts-ignore
import scrollbarPlugin from '@windicss/plugin-scrollbar';
// @ts-ignore
import questionMarkPlugin from '@windicss/plugin-question-mark';
// @ts-ignore
import heropatternsPlugin from '@windicss/plugin-heropatterns';
// @ts-ignore
import interactionVariantsPlugin from '@windicss/plugin-interaction-variants';

const primary = antdColors.generate('#1890ff');

export default defineConfig({
  preflight: false,
  attributify: true,
  plugins: [
    aspectRatioPlugin,
    formsPlugin,
    filtersPlugin,
    lineClampPlugin,
    scrollSnapPlugin,
    typographyPlugin,
    animationsPlugin,
    scrollbarPlugin,
    questionMarkPlugin,
    heropatternsPlugin,
    interactionVariantsPlugin,
  ],
  theme: {
    extend: {
      screens: {
        sm: '576px',
        md: '768px',
        lg: '992px',
        xl: '1200px',
        '2xl': '1600px',
        xxl: '1600px',
      },
      flexGrow: {
        2: '2',
        3: '3',
        4: '4',
        5: '5',
        6: '6',
        7: '7',
        8: '8',
      },
      flexShrink: {
        2: '2',
        3: '3',
        4: '4',
        5: '5',
        6: '6',
        7: '7',
        8: '8',
      },
      colors: {
        pink: {
          50: '#fdf2f8',
          100: '#fce7f3',
          200: '#fbcfe8',
          300: '#f9a8d4',
          400: '#f472b6',
          500: '#ec4899',
          600: '#db2777',
          700: '#be185d',
          800: '#9d174d',
          900: '#831843',
        },
        rose: {
          50: '#fff1f2',
          100: '#ffe4e6',
          200: '#fecdd3',
          300: '#fda4af',
          400: '#fb7185',
          500: '#f43f5e',
          600: '#e11d48',
          700: '#be123c',
          800: '#9f1239',
          900: '#881337',
        },
        red: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          ...antdColors.red.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.red[5],
          DEFAULT: antdColors.red[5],
          'lighten-5': antdColors.red[0],
          'lighten-4': antdColors.red[1],
          'lighten-3': antdColors.red[2],
          'lighten-2': antdColors.red[3],
          'lighten-1': antdColors.red[4],
          'darken-1': antdColors.red[6],
          'darken-2': antdColors.red[7],
          'darken-3': antdColors.red[8],
          'darken-4': antdColors.red[9],
        },
        orange: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
          ...antdColors.orange.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.orange[5],
          DEFAULT: antdColors.orange[5],
          'lighten-5': antdColors.orange[0],
          'lighten-4': antdColors.orange[1],
          'lighten-3': antdColors.orange[2],
          'lighten-2': antdColors.orange[3],
          'lighten-1': antdColors.orange[4],
          'darken-1': antdColors.orange[6],
          'darken-2': antdColors.orange[7],
          'darken-3': antdColors.orange[8],
          'darken-4': antdColors.orange[9],
        },
        yellow: {
          50: '#fefce8',
          100: '#fef9c3',
          200: '#fef08a',
          300: '#fde047',
          400: '#facc15',
          500: '#eab308',
          600: '#ca8a04',
          700: '#a16207',
          800: '#854d0e',
          900: '#713f12',
          ...antdColors.yellow.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.yellow[5],
          DEFAULT: antdColors.yellow[5],
          'lighten-5': antdColors.yellow[0],
          'lighten-4': antdColors.yellow[1],
          'lighten-3': antdColors.yellow[2],
          'lighten-2': antdColors.yellow[3],
          'lighten-1': antdColors.yellow[4],
          'darken-1': antdColors.yellow[6],
          'darken-2': antdColors.yellow[7],
          'darken-3': antdColors.yellow[8],
          'darken-4': antdColors.yellow[9],
        },
        amber: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        lime: {
          50: '#f7fee7',
          100: '#ecfccb',
          200: '#d9f99d',
          300: '#bef264',
          400: '#a3e635',
          500: '#84cc16',
          600: '#65a30d',
          700: '#4d7c0f',
          800: '#3f6212',
          900: '#365314',
          ...antdColors.lime.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.lime[5],
          DEFAULT: antdColors.lime[5],
          'lighten-5': antdColors.lime[0],
          'lighten-4': antdColors.lime[1],
          'lighten-3': antdColors.lime[2],
          'lighten-2': antdColors.lime[3],
          'lighten-1': antdColors.lime[4],
          'darken-1': antdColors.lime[6],
          'darken-2': antdColors.lime[7],
          'darken-3': antdColors.lime[8],
          'darken-4': antdColors.lime[9],
        },
        green: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          ...antdColors.green.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.green[5],
          DEFAULT: antdColors.green[5],
          'lighten-5': antdColors.green[0],
          'lighten-4': antdColors.green[1],
          'lighten-3': antdColors.green[2],
          'lighten-2': antdColors.green[3],
          'lighten-1': antdColors.green[4],
          'darken-1': antdColors.green[6],
          'darken-2': antdColors.green[7],
          'darken-3': antdColors.green[8],
          'darken-4': antdColors.green[9],
        },
        emerald: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
        teal: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
        },
        cyan: {
          50: '#ecfeff',
          100: '#cffafe',
          200: '#a5f3fc',
          300: '#67e8f9',
          400: '#22d3ee',
          500: '#06b6d4',
          600: '#0891b2',
          700: '#0e7490',
          800: '#155e75',
          900: '#164e63',
          ...antdColors.cyan.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.cyan[5],
          DEFAULT: antdColors.cyan[5],
          'lighten-5': antdColors.cyan[0],
          'lighten-4': antdColors.cyan[1],
          'lighten-3': antdColors.cyan[2],
          'lighten-2': antdColors.cyan[3],
          'lighten-1': antdColors.cyan[4],
          'darken-1': antdColors.cyan[6],
          'darken-2': antdColors.cyan[7],
          'darken-3': antdColors.cyan[8],
          'darken-4': antdColors.cyan[9],
        },
        blue: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          ...antdColors.blue.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.blue[5],
          DEFAULT: antdColors.blue[5],
          'lighten-5': antdColors.blue[0],
          'lighten-4': antdColors.blue[1],
          'lighten-3': antdColors.blue[2],
          'lighten-2': antdColors.blue[3],
          'lighten-1': antdColors.blue[4],
          'darken-1': antdColors.blue[6],
          'darken-2': antdColors.blue[7],
          'darken-3': antdColors.blue[8],
          'darken-4': antdColors.blue[9],
        },
        indigo: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        purple: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7e22ce',
          800: '#6b21a8',
          900: '#581c87',
          ...antdColors.purple.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.purple[5],
          DEFAULT: antdColors.purple[5],
          'lighten-5': antdColors.purple[0],
          'lighten-4': antdColors.purple[1],
          'lighten-3': antdColors.purple[2],
          'lighten-2': antdColors.purple[3],
          'lighten-1': antdColors.purple[4],
          'darken-1': antdColors.purple[6],
          'darken-2': antdColors.purple[7],
          'darken-3': antdColors.purple[8],
          'darken-4': antdColors.purple[9],
        },
        violet: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
        },
        fuchsia: {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
        },
        gray: {
          50: '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#71717a',
          600: '#52525b',
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
          1: '#fff',
          2: '#fafafa',
          3: '#f5f5f5',
          4: '#f0f0f0',
          5: '#d9d9d9',
          6: '#bfbfbf',
          7: '#8c8c8c',
          8: '#595959',
          9: '#434343',
          10: '#262626',
          11: '#1f1f1f',
          12: '#141414',
          13: '#000',
          default: '#8c8c8c',
          DEFAULT: '#8c8c8c',
          'lighten-6': '#fff',
          'lighten-5': '#fafafa',
          'lighten-4': '#f5f5f5',
          'lighten-3': '#f0f0f0',
          'lighten-2': '#d9d9d9',
          'lighten-1': '#bfbfbf',
          'darken-1': '#595959',
          'darken-2': '#434343',
          'darken-3': '#262626',
          'darken-4': '#1f1f1f',
          'darken-5': '#141414',
          'darken-6': '#000',
        },
        blueGray: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        coolGray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        warmGray: {
          50: '#fafaf9',
          100: '#f5f5f4',
          200: '#e7e5e4',
          300: '#d6d3d1',
          400: '#a8a29e',
          500: '#78716c',
          600: '#57534e',
          700: '#44403c',
          800: '#292524',
          900: '#1c1917',
        },
        trueGray: {
          50: '#fafafa',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
        },
        sky: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        volcano: {
          ...antdColors.volcano.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.volcano[5],
          DEFAULT: antdColors.volcano[5],
          'lighten-5': antdColors.volcano[0],
          'lighten-4': antdColors.volcano[1],
          'lighten-3': antdColors.volcano[2],
          'lighten-2': antdColors.volcano[3],
          'lighten-1': antdColors.volcano[4],
          'darken-1': antdColors.volcano[6],
          'darken-2': antdColors.volcano[7],
          'darken-3': antdColors.volcano[8],
          'darken-4': antdColors.volcano[9],
        },
        gold: {
          ...antdColors.gold.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.gold[5],
          DEFAULT: antdColors.gold[5],
          'lighten-5': antdColors.gold[0],
          'lighten-4': antdColors.gold[1],
          'lighten-3': antdColors.gold[2],
          'lighten-2': antdColors.gold[3],
          'lighten-1': antdColors.gold[4],
          'darken-1': antdColors.gold[6],
          'darken-2': antdColors.gold[7],
          'darken-3': antdColors.gold[8],
          'darken-4': antdColors.gold[9],
        },
        geekBlue: {
          ...antdColors.geekblue.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.geekblue[5],
          DEFAULT: antdColors.geekblue[5],
          'lighten-5': antdColors.geekblue[0],
          'lighten-4': antdColors.geekblue[1],
          'lighten-3': antdColors.geekblue[2],
          'lighten-2': antdColors.geekblue[3],
          'lighten-1': antdColors.geekblue[4],
          'darken-1': antdColors.geekblue[6],
          'darken-2': antdColors.geekblue[7],
          'darken-3': antdColors.geekblue[8],
          'darken-4': antdColors.geekblue[9],
        },
        magenta: {
          ...antdColors.magenta.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.magenta[5],
          DEFAULT: antdColors.magenta[5],
          'lighten-5': antdColors.magenta[0],
          'lighten-4': antdColors.magenta[1],
          'lighten-3': antdColors.magenta[2],
          'lighten-2': antdColors.magenta[3],
          'lighten-1': antdColors.magenta[4],
          'darken-1': antdColors.magenta[6],
          'darken-2': antdColors.magenta[7],
          'darken-3': antdColors.magenta[8],
          'darken-4': antdColors.magenta[9],
        },
        primary: {
          ...primary.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: primary[5],
          DEFAULT: primary[5],
          'lighten-5': primary[0],
          'lighten-4': primary[1],
          'lighten-3': primary[2],
          'lighten-2': primary[3],
          'lighten-1': primary[4],
          'darken-1': primary[6],
          'darken-2': primary[7],
          'darken-3': primary[8],
          'darken-4': primary[9],
        },
        success: {
          ...antdColors.green.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.green[5],
          DEFAULT: antdColors.green[5],
          'lighten-5': antdColors.green[0],
          'lighten-4': antdColors.green[1],
          'lighten-3': antdColors.green[2],
          'lighten-2': antdColors.green[3],
          'lighten-1': antdColors.green[4],
          'darken-1': antdColors.green[6],
          'darken-2': antdColors.green[7],
          'darken-3': antdColors.green[8],
          'darken-4': antdColors.green[9],
        },
        warning: {
          ...antdColors.gold.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.gold[5],
          DEFAULT: antdColors.gold[5],
          'lighten-5': antdColors.gold[0],
          'lighten-4': antdColors.gold[1],
          'lighten-3': antdColors.gold[2],
          'lighten-2': antdColors.gold[3],
          'lighten-1': antdColors.gold[4],
          'darken-1': antdColors.gold[6],
          'darken-2': antdColors.gold[7],
          'darken-3': antdColors.gold[8],
          'darken-4': antdColors.gold[9],
        },
        danger: {
          ...antdColors.red.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.red[5],
          DEFAULT: antdColors.red[5],
          'lighten-5': antdColors.red[0],
          'lighten-4': antdColors.red[1],
          'lighten-3': antdColors.red[2],
          'lighten-2': antdColors.red[3],
          'lighten-1': antdColors.red[4],
          'darken-1': antdColors.red[6],
          'darken-2': antdColors.red[7],
          'darken-3': antdColors.red[8],
          'darken-4': antdColors.red[9],
        },
        error: {
          ...antdColors.red.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.red[5],
          DEFAULT: antdColors.red[5],
          'lighten-5': antdColors.red[0],
          'lighten-4': antdColors.red[1],
          'lighten-3': antdColors.red[2],
          'lighten-2': antdColors.red[3],
          'lighten-1': antdColors.red[4],
          'darken-1': antdColors.red[6],
          'darken-2': antdColors.red[7],
          'darken-3': antdColors.red[8],
          'darken-4': antdColors.red[9],
        },
        info: {
          ...antdColors.blue.reduce(
            (acc, cur, idx) => ({
              ...acc,
              [idx + 1]: cur,
            }),
            {},
          ),
          default: antdColors.blue[5],
          DEFAULT: antdColors.blue[5],
          'lighten-5': antdColors.blue[0],
          'lighten-4': antdColors.blue[1],
          'lighten-3': antdColors.blue[2],
          'lighten-2': antdColors.blue[3],
          'lighten-1': antdColors.blue[4],
          'darken-1': antdColors.blue[6],
          'darken-2': antdColors.blue[7],
          'darken-3': antdColors.blue[8],
          'darken-4': antdColors.blue[9],
        },
        transparent: 'transparent',
        current: 'currentColor',
        black: '#000',
        white: '#fff',
      },
    },
  },
});
